version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
     image: redis:alpine

  catalogs:
    image: ${DOCKER_REGISTRY-}catalogs
    build:
      context: .
      dockerfile: src/Api/Catalog/Catalogs.Api/Catalogs/Dockerfile

  baskets.api:
    image: ${DOCKER_REGISTRY-}basketsapi
    build:
      context: .
      dockerfile: src/Api/basket/Baskets.Api/Dockerfile

volumes:
  mongo_data:
